# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_layout_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 826)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 826))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tool_life_box = QtWidgets.QGroupBox(self.centralwidget)
        self.tool_life_box.setMinimumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tool_life_box.setFont(font)
        self.tool_life_box.setAlignment(QtCore.Qt.AlignCenter)
        self.tool_life_box.setObjectName("tool_life_box")
        self.tool_img = QtWidgets.QLabel(self.tool_life_box)
        self.tool_img.setGeometry(QtCore.QRect(90, 30, 281, 251))
        self.tool_img.setMinimumSize(QtCore.QSize(0, 0))
        self.tool_img.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tool_img.setFont(font)
        self.tool_img.setText("")
        self.tool_img.setObjectName("tool_img")
        self.cut_num = QtWidgets.QLabel(self.tool_life_box)
        self.cut_num.setGeometry(QtCore.QRect(190, 120, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cut_num.setFont(font)
        self.cut_num.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cut_num.setObjectName("cut_num")
        self.wear = QtWidgets.QLabel(self.tool_life_box)
        self.wear.setGeometry(QtCore.QRect(190, 190, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.wear.setFont(font)
        self.wear.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wear.setObjectName("wear")
        self.label = QtWidgets.QLabel(self.tool_life_box)
        self.label.setGeometry(QtCore.QRect(190, 90, 131, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tool_life_box)
        self.label_2.setGeometry(QtCore.QRect(200, 170, 101, 21))
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.tool_life_box, 0, 0, 1, 1)
        self.info_box = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.info_box.setFont(font)
        self.info_box.setAlignment(QtCore.Qt.AlignCenter)
        self.info_box.setObjectName("info_box")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.info_box)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.start = QtWidgets.QPushButton(self.info_box)
        self.start.setObjectName("start")
        self.gridLayout_10.addWidget(self.start, 1, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.rotate_val = QtWidgets.QLabel(self.info_box)
        self.rotate_val.setObjectName("rotate_val")
        self.gridLayout_9.addWidget(self.rotate_val, 1, 1, 1, 1)
        self.round_val = QtWidgets.QLabel(self.info_box)
        self.round_val.setObjectName("round_val")
        self.gridLayout_9.addWidget(self.round_val, 0, 1, 1, 1)
        self.rotate = QtWidgets.QLabel(self.info_box)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rotate.setFont(font)
        self.rotate.setAlignment(QtCore.Qt.AlignCenter)
        self.rotate.setObjectName("rotate")
        self.gridLayout_9.addWidget(self.rotate, 1, 0, 1, 1)
        self.round = QtWidgets.QLabel(self.info_box)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.round.setFont(font)
        self.round.setAlignment(QtCore.Qt.AlignCenter)
        self.round.setObjectName("round")
        self.gridLayout_9.addWidget(self.round, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.info_box, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 3, 0, 1, 1)
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setContentsMargins(-1, -1, 0, -1)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.error_box = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.error_box.setFont(font)
        self.error_box.setAlignment(QtCore.Qt.AlignCenter)
        self.error_box.setObjectName("error_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.error_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tool_life = QtWidgets.QLabel(self.error_box)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tool_life.setFont(font)
        self.tool_life.setObjectName("tool_life")
        self.gridLayout_11.addWidget(self.tool_life, 2, 0, 1, 1)
        self.tooler_error_val = QtWidgets.QLabel(self.error_box)
        self.tooler_error_val.setMaximumSize(QtCore.QSize(50, 50))
        self.tooler_error_val.setText("")
        self.tooler_error_val.setObjectName("tooler_error_val")
        self.gridLayout_11.addWidget(self.tooler_error_val, 0, 1, 1, 1)
        self.matter_val = QtWidgets.QLabel(self.error_box)
        self.matter_val.setMaximumSize(QtCore.QSize(50, 50))
        self.matter_val.setText("")
        self.matter_val.setObjectName("matter_val")
        self.gridLayout_11.addWidget(self.matter_val, 1, 1, 1, 1)
        self.tool_life_val = QtWidgets.QLabel(self.error_box)
        self.tool_life_val.setMaximumSize(QtCore.QSize(50, 50))
        self.tool_life_val.setText("")
        self.tool_life_val.setObjectName("tool_life_val")
        self.gridLayout_11.addWidget(self.tool_life_val, 2, 1, 1, 1)
        self.tooler_error = QtWidgets.QLabel(self.error_box)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tooler_error.setFont(font)
        self.tooler_error.setObjectName("tooler_error")
        self.gridLayout_11.addWidget(self.tooler_error, 0, 0, 1, 1)
        self.matter = QtWidgets.QLabel(self.error_box)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.matter.setFont(font)
        self.matter.setObjectName("matter")
        self.gridLayout_11.addWidget(self.matter, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_11, 1, 0, 1, 1)
        self.ng_good = QtWidgets.QLabel(self.error_box)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ng_good.setFont(font)
        self.ng_good.setObjectName("ng_good")
        self.gridLayout_4.addWidget(self.ng_good, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridlayout.addWidget(self.error_box, 0, 1, 1, 1)
        self.img = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(100)
        self.img.setFont(font)
        self.img.setText("")
        self.img.setObjectName("img")
        self.gridlayout.addWidget(self.img, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridlayout, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.verticalLayout_9.addWidget(self.name)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setMinimumSize(QtCore.QSize(352, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.logo.setFont(font)
        self.logo.setObjectName("logo")
        self.verticalLayout_8.addWidget(self.logo)
        self.co_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.co_name.setFont(font)
        self.co_name.setObjectName("co_name")
        self.verticalLayout_8.addWidget(self.co_name)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.camera_rg = QtWidgets.QLabel(self.centralwidget)
        self.camera_rg.setMaximumSize(QtCore.QSize(50, 50))
        self.camera_rg.setText("")
        self.camera_rg.setObjectName("camera_rg")
        self.gridLayout_3.addWidget(self.camera_rg, 1, 1, 1, 1)
        self.server_rg = QtWidgets.QLabel(self.centralwidget)
        self.server_rg.setMaximumSize(QtCore.QSize(50, 50))
        self.server_rg.setText("")
        self.server_rg.setObjectName("server_rg")
        self.gridLayout_3.addWidget(self.server_rg, 0, 1, 1, 1)
        self.server = QtWidgets.QLabel(self.centralwidget)
        self.server.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.server.setFont(font)
        self.server.setAlignment(QtCore.Qt.AlignCenter)
        self.server.setObjectName("server")
        self.gridLayout_3.addWidget(self.server, 0, 0, 1, 1)
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.camera.setFont(font)
        self.camera.setAlignment(QtCore.Qt.AlignCenter)
        self.camera.setObjectName("camera")
        self.gridLayout_3.addWidget(self.camera, 1, 0, 1, 1)
        self.server_info = QtWidgets.QPushButton(self.centralwidget)
        self.server_info.setMaximumSize(QtCore.QSize(200, 300))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.server_info.setFont(font)
        self.server_info.setObjectName("server_info")
        self.gridLayout_3.addWidget(self.server_info, 0, 2, 1, 1)
        self.camera_info = QtWidgets.QPushButton(self.centralwidget)
        self.camera_info.setMaximumSize(QtCore.QSize(200, 300))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.camera_info.setFont(font)
        self.camera_info.setObjectName("camera_info")
        self.gridLayout_3.addWidget(self.camera_info, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tool_life_box.setTitle(_translate("MainWindow", "Tool-life"))
        self.cut_num.setText(_translate("MainWindow", "90"))
        self.wear.setText(_translate("MainWindow", "80"))
        self.label.setText(_translate("MainWindow", "절단 횟수"))
        self.label_2.setText(_translate("MainWindow", "마모도"))
        self.info_box.setTitle(_translate("MainWindow", "절단봉 정보"))
        self.start.setText(_translate("MainWindow", "start"))
        self.rotate_val.setText(_translate("MainWindow", "90        도"))
        self.round_val.setText(_translate("MainWindow", "200        mm"))
        self.rotate.setText(_translate("MainWindow", "- 회전"))
        self.round.setText(_translate("MainWindow", "- 둘레"))
        self.error_box.setTitle(_translate("MainWindow", "불량 검출"))
        self.tool_life.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">툴라이프 수명</span></p></body></html>"))
        self.tooler_error.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">절단봉 툴러 불량</span></p></body></html>"))
        self.matter.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">절단봉 이물질</span></p></body></html>"))
        self.ng_good.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">NG / GOOD</span></p></body></html>"))
        self.name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">절단봉 불량 검출</p><p align=\"center\">프로그램</p></body></html>"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">logo</p></body></html>"))
        self.co_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">samkwang motors</p></body></html>"))
        self.server.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">SERVER</span></p></body></html>"))
        self.camera.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">CAMERA</span></p></body></html>"))
        self.server_info.setText(_translate("MainWindow", "서버정보"))
        self.camera_info.setText(_translate("MainWindow", "카메라정보"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

